version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true

file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: scripts/stop_server
      timeout: 3600
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 3600
      runas: root